spring.application.name=seshat-rpg-auxiliary

# Essa parte será modificada no futuro para não expor os dados no git.


# Configurando o banco de dados
#spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.ssvgawyotinvuyxmvbfc&password=Henrycomefrango369
spring.datasource.driver-class-name=org.postgresql.Driver


# Secret para o token

api.security.token.secret=HenryGostaDeFrango